from django.conf.urls.defaults import *
from django.views.generic import list_detail, create_update, date_based
from gadai.appgadai.kasirgerai.views import *
from django.views.generic.simple import direct_to_template
from django.forms import ModelForm

urlpatterns = patterns('',
    url(r'^laporan_permintaan_titipan_gu/$',laporan_permintaan_titipan_gu),
    url(r'^(?P<object_id>\d+)/eksekusi_app_keu_gu/$',eksekusi_app_keu_gu),	
    url(r'^(?P<object_id>\d+)/oto_app_keu_gu/$', oto_app_keu_gu),
    url(r'^list_app_keu_gu/$',list_app_keu_gu),
    url(r'^(?P<object_id>\d+)/tampil_app_keu_gu/$', tampil_app_keu_gu),
    url(r'^(?P<object_id>\d+)/app_keu_gu/$', app_keu_gu),
    url(r'^(?P<object_id>\d+)/cetak_transaksi_bank_pusat/$', cetak_transaksi_bank_pusat),
    url(r'^(?P<object_id>\d+)/cetak_transaksi_kas_pusat/$', cetak_transaksi_kas_pusat),
    url(r'^(?P<object_id>\d+)/transaksi_bank_pusat/$', transaksi_bank_pusat),
    url(r'^(?P<object_id>\d+)/transaksi_kas_pusat/$', transaksi_kas_pusat),
    url(r'^(?P<object_id>\d+)/all_transaksi_bank_pusat/$', all_transaksi_bank_pusat),
    url(r'^(?P<object_id>\d+)/all_transaksi_kas_pusat/$', all_transaksi_kas_pusat),
    url(r'^kwitansi_gu_adm/$',kwitansi_gu_adm),
    url(r'^(?P<object_id>\d+)/input_pengembalian_gu/$',input_pengembalian_gu),
    url(r'^(?P<object_id>\d+)/tampil_pengembalian_gu/$', tampil_pengembalian_gu),
    url(r'^(?P<object_id>\d+)/kembaligu/$', kembaligu),
    url(r'^mastertiket_ayda_gerai/$',mastertiket_ayda_gerai),
    url(r'^(?P<object_id>\d+)/denominasi/$',denominasi),
    url(r'^(?P<object_id>\d+)/mastertiket_gabungan_kasir/$', mastertiket_gabungan_kasir),
    url(r'^(?P<object_id>\d+)/data_lunas_kasir/$', data_lunas_kasir),
    url(r'^(?P<object_id>\d+)/slip_setoran_titipan_pelunasan/$', slip_setoran_titipan_pelunasan),
    url(r'^(?P<object_id>\d+)/data_titipan_pelunasan/$', data_titipan_pelunasan),
    url(r'^(?P<object_id>\d+)/cetak_all_transaksi_kas/$', cetak_all_transaksi_kas),
    url(r'^(?P<object_id>\d+)/cetak_all_transaksi_bank/$', cetak_all_transaksi_bank),
    url(r'^(?P<object_id>\d+)/posting_akhir_hari/$', posting_akhir_hari),
    url(r'^(?P<object_id>\d+)/verifikasi_kasir_gu/$',verifikasi_kasir_gu),
    url(r'^(?P<object_id>\d+)/app/$',app),
    url(r'^(?P<object_id>\d+)/app_gu/$',app_gu),
    url(r'^(?P<object_id>\d+)/laporan_pelunasan_titipan/$', laporan_pelunasan_titipan),
    url(r'^(?P<object_id>\d+)/laporan_pelunasan/$', laporan_pelunasan),
    url(r'^(?P<object_id>\d+)/laporan_pencairan/$', laporan_pencairan),
    url(r'^(?P<object_id>\d+)/mastertiket_antargerai/$', mastertiket_antargerai),
    url(r'^(?P<object_id>\d+)/mastertiket_uangmuka/$', mastertiket_uangmuka),
    url(r'^(?P<object_id>\d+)/jurnal_umum/$', jurnal_umum),
    url(r'^(?P<object_id>\d+)/gl_val/$',gl_val),
    url(r'^(?P<object_id>\d+)/cetak_all_transaksi/$',cetak_all_transaksi),
    url(r'^(?P<object_id>\d+)/cetak_data_kredit/$',cetak_data_kredit),
    url(r'^cariplns/$', cariplns),
    url(r'^lunas_kasir/$', lunas_kasir),
    url(r'^(?P<object_id>\d+)/uangmuka/$', uangmuka),
    url(r'^(?P<object_id>\d+)/all_transaksi/$', all_transaksi),
    url(r'^(?P<object_id>\d+)/all_transaksi_kas/$', all_transaksi_kas),
    url(r'^(?P<object_id>\d+)/all_transaksi_bank/$', all_transaksi_bank),
    url(r'^(?P<object_id>\d+)/all_approve/$', all_approve),
    url(r'^postting_all_jurnal/$', postting_all_jurnal),
    url(r'^(?P<object_id>\d+)/all_transaksi_jurnal/$', all_transaksi_jurnal),
    url(r'^(?P<object_id>\d+)/view_cabang/$', view_cabang),
    url(r'^(?P<object_id>\d+)/master_tiket_kasir_pelunasan/$', master_tiket_kasir_pelunasan),
    url(r'^(?P<object_id>\d+)/inputkasir_pelunasan/$',inputkasir_pelunasan),
    url(r'^(?P<object_id>\d+)/mcc/$',mcc),
    url(r'^(?P<object_id>\d+)/print_loan/$',print_loan),
    url(r'^(?P<object_id>\d+)/mcc_image/$',mcc_image),
    url(r'^(?P<object_id>\d+)/approve_pelunasan_kasir/$',approve_pelunasan_kasir),
    url(r'^(?P<object_id>\d+)/kasir_pelunasan/$',kasir_pelunasan),
    url(r'^data_approve/$',data_approve),
    url(r'^lunas/$',lunas),
    url(r'^(?P<object_id>\d+)/mastertiket_gl_gl/$', mastertiket_gl_gl),
    url(r'^(?P<object_id>\d+)/mastertiket_pencairan_kasir/$', mastertiket_pencairan_kasir),
    url(r'^(?P<object_id>\d+)/mastertiket_uji_coba_kasir/$',mastertiket_uji_coba_kasir),
    #url(r'^(?P<object_id>\d+)/mastertiket_uji_coba_kasir/$',mastertiket_uji_coba_kasir),
    url(r'^(?P<object_id>\d+)/kasir/$',kasir),###19 juni
    url(r'^(?P<object_id>\d+)/inputkasir/$',inputkasir),###19 juni
    url(r'^(?P<object_id>\d+)/slip_validasi/$',slip_validasi),
    ###PENGEMBALIAN KE NASABAh
    url(r'^(?P<object_id>\d+)/pengembalian/$',pengembalian),
    url(r'^cari/$', cari),
    url(r'^carikembalian/$', carikembalian),
    url(r'^(?P<object_id>\d+)/input_pengembalian/$',input_pengembalian),
)
